# Generated by Django 5.2.6 on 2025-10-19 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Ijara', 'verbose_name_plural': 'Ijaralar'},
        ),
        migrations.AlterModelOptions(
            name='rentalitem',
            options={'verbose_name': 'Ijara mahsuloti', 'verbose_name_plural': 'Ijara mahsulotlari'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'Asbob', 'verbose_name_plural': 'Asboblar'},
        ),
        migrations.AlterModelOptions(
            name='toolcategory',
            options={'verbose_name': 'Asbob kategoriyasi', 'verbose_name_plural': 'Asbob kategoriyalari'},
        ),
        migrations.AddField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kunlik narx'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tool', verbose_name='Asbob'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.toolcategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kunlik narx'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Asbob nomi'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='quantity_available',
            field=models.IntegerField(verbose_name='Mavjud soni'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='quantity_total',
            field=models.IntegerField(verbose_name='Jami soni'),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategoriya nomi'),
        ),
    ]
