# Generated by Django 5.2.6 on 2025-10-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_options_alter_rental_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalitem',
            options={},
        ),
    ]
